{{-- Ported from teamat.ai.studio (pages/home.html). Identical on all seven marketing pages. --}}
<footer id="main-footer" class="bg-[#0A0A0A] text-white border-t-[0.5px] border-white/10">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-12">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 lg:gap-8 pb-12">
            <div class="space-y-4"><a id="footer-brand-link" class="inline-block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] rounded-lg" aria-label="الرئيسية - تيمات" href="/" data-discover="true">
                <div class="inline-flex items-center gap-3 select-none "><svg width="36" height="36" viewBox="0 0 52 52" role="img" aria-label="شعار تيمات" class="shrink-0 transition-transform duration-200"><rect width="52" height="52" rx="13" fill="#C8FF00"></rect><rect x="11" y="13" width="30" height="8" rx="2.5" fill="#0A0A0A"></rect><rect x="21" y="21" width="10" height="20" rx="2.5" fill="#0A0A0A"></rect></svg><span class="font-arabic font-extrabold tracking-tight text-2xl text-white">تيمات</span></div></a>
                <p class="text-white/70 text-sm leading-relaxed max-w-[260px]">منصة سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً.</p>
                <div class="flex items-center gap-2 text-xs text-white/50 pt-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin w-3.5 h-3.5 text-[#C8FF00] shrink-0" aria-hidden="true"><path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"></path><circle cx="12" cy="10" r="3"></circle></svg><span>تيمات — الرياض، المملكة العربية السعودية</span></div></div>
            <div>
                <h2 class="text-xs font-inter font-extrabold uppercase tracking-[2px] text-[#C8FF00] mb-4">المنتج</h2>
                <ul class="space-y-2.5 text-sm">
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/how-it-works" data-discover="true">كيف تعمل المنصة</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/for-companies" data-discover="true">حلول الشركات</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/for-providers" data-discover="true">شبكة مزودي الخدمة</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/activities" data-discover="true">دليل الأنشطة</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/model" data-discover="true">النموذج المالي</a></li></ul></div>
            <div>
                <h2 class="text-xs font-inter font-extrabold uppercase tracking-[2px] text-[#C8FF00] mb-4">المنصة</h2>
                <ul class="space-y-2.5 text-sm">
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/for-companies" data-discover="true">عن تيمات</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/contact" data-discover="true">طلب عرض مخصص</a></li>
                    <li><a class="text-white/70 hover:text-[#C8FF00] transition-colors duration-150 inline-block py-0.5" href="/for-providers#join" data-discover="true">انضمام مزودي الخدمة</a></li></ul></div>
            <div>
                <h2 class="text-xs font-inter font-extrabold uppercase tracking-[2px] text-[#C8FF00] mb-4">التواصل</h2>
                <div class="space-y-3 text-sm"><a href="mailto:contact@teamat.app" class="flex items-center gap-2.5 text-white/70 hover:text-[#C8FF00] transition-colors duration-150 group"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mail w-4 h-4 text-[#C8FF00] shrink-0" aria-hidden="true"><path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"></path><rect x="2" y="4" width="20" height="16" rx="2"></rect></svg><span dir="ltr" class="font-inter text-xs sm:text-sm">contact@teamat.app</span></a><a href="https://wa.me/966500000000" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2.5 text-white/70 hover:text-[#C8FF00] transition-colors duration-150 group"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle w-4 h-4 text-[#C8FF00] shrink-0" aria-hidden="true"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"></path></svg><span dir="ltr" class="font-inter text-xs sm:text-sm">+966 50 000 0000</span></a>
                    <div class="flex items-center gap-2.5 text-white/50 text-xs pt-1"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-globe w-4 h-4 text-[#C8FF00] shrink-0" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"></path><path d="M2 12h20"></path></svg><span dir="ltr" class="font-inter">teamat.app</span></div></div></div></div>
        <div class="pt-8 border-t-[0.5px] border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-white/50 font-light">
            <p>© 2026 تيمات · جميع الحقوق محفوظة</p>
            <div class="flex items-center gap-6"><span class="font-inter tracking-wider uppercase text-[10px] text-[#C8FF00]">SAUDI ARABIA · B2B SAAS</span></div></div></div></footer>
