@extends('layouts.marketing', [
    'headerTheme' => 'dark',
    'activeNav' => '',
])

@section('title', 'تيمات | فعاليات متكررة تلقائياً للموظفين')
@section('description', 'تواصل مع فريق تيمات لطلب عرض مخصص لشركتك أو الاستفسار عن الشراكات وبدء تفعيل مجتمعات الموظفين.')

@section('content')
<script type="application/ld+json">{"@@context":"https://schema.org","@@type":"Organization","name":"تيمات | Teamat","url":"https://teamat.app","logo":"https://teamat.app/favicon.svg","description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة.","address":{"@@type":"PostalAddress","addressLocality":"الرياض","addressCountry":"SA"},"contactPoint":{"@@type":"ContactPoint","email":"contact@teamat.app","contactType":"customer support","areaServed":"SA","availableLanguage":["Arabic"]}}</script><script type="application/ld+json">{"@@context":"https://schema.org","@@type":"SoftwareApplication","name":"Teamat Platform | منصة تيمات","operatingSystem":"Web","applicationCategory":"BusinessApplication","offers":{"@@type":"Offer","price":"0","priceCurrency":"SAR","availability":"https://schema.org/InStock"},"description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة."}</script>
<section id="contact-hero" class="bg-[#0A0A0A] text-white pt-36 pb-16 px-4 sm:px-6 lg:px-8 border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -top-24 -left-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto relative z-10">
        <div class="max-w-[740px] space-y-4"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الخطوة الأولى</span>
            <h1 class="text-3xl sm:text-4xl md:text-5xl font-extrabold font-arabic text-white leading-tight">ابدأ تحويل الاهتمامات إلى استمرار</h1>
            <p class="text-base sm:text-lg text-white/80 leading-[1.8] pt-1">أرسل بيانات شركتك وسيقوم فريق تيمات بالرد عليك بعرض مخصص خلال يوم عمل واحد.</p></div></div></section>
<section id="contact-form-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-start">
            <div class="lg:col-span-8">
                <form id="main-contact-lead-form" novalidate="" class="p-6 sm:p-8 lg:p-10 rounded-[16px] bg-white border-[0.5px] border-[#0A0A0A]/10 space-y-6">
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <div><label for="lead-name" class="block text-sm font-bold text-[#0A0A0A] mb-2">الاسم الكامل <span class="text-red-500">*</span></label><input id="lead-name" required="" placeholder="مثال: محمد بن سعود" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors border-[#0A0A0A]/15" type="text" value=""></div>
                        <div><label for="lead-company" class="block text-sm font-bold text-[#0A0A0A] mb-2">اسم الشركة <span class="text-red-500">*</span></label><input id="lead-company" required="" placeholder="مثال: شركة الرواد للتقنية" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors border-[#0A0A0A]/15" type="text" value=""></div></div>
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <div><label for="lead-email" class="block text-sm font-bold text-[#0A0A0A] mb-2">البريد الإلكتروني للعمل <span class="text-red-500">*</span></label><input id="lead-email" dir="ltr" required="" placeholder="name@company.com" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm text-right focus:bg-white transition-colors border-[#0A0A0A]/15" type="email" value=""></div>
                        <div><label for="lead-phone" class="block text-sm font-bold text-[#0A0A0A] mb-2">رقم الجوال <span class="text-red-500">*</span></label><input id="lead-phone" dir="ltr" required="" placeholder="05XXXXXXXX" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm text-right focus:bg-white transition-colors border-[#0A0A0A]/15" type="tel" value=""></div></div>
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <div><label for="lead-employees" class="block text-sm font-bold text-[#0A0A0A] mb-2">عدد الموظفين <span class="text-red-500">*</span></label><select id="lead-employees" required="" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors cursor-pointer border-[#0A0A0A]/15"><option value="">اختر نطاق عدد الموظفين</option><option value="less-than-50">أقل من ٥٠ موظفاً</option><option value="50-200">٥٠ إلى ٢٠٠ موظف</option><option value="201-500">٢٠١ إلى ٥٠٠ موظف</option><option value="500-plus">أكثر من ٥٠٠ موظف</option></select></div>
                        <div><label for="lead-track" class="block text-sm font-bold text-[#0A0A0A] mb-2">المسار المالي المفضّل <span class="text-red-500">*</span></label><select id="lead-track" required="" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors cursor-pointer border-[#0A0A0A]/15"><option value="">اختر المسار المالي</option><option value="community-wallet">مسار محفظة المجتمع (الشركة تتحمل التكلفة)</option><option value="employee-pay">مسار دفع الموظف (الموظف يدفع حصته)</option><option value="undecided">غير محدد بعد (نحتاج استشارة)</option></select></div></div>
                    <div><label for="lead-message" class="block text-sm font-bold text-[#0A0A0A] mb-2">رسالة أو ملاحظات إضافية (اختياري)</label><textarea id="lead-message" rows="4" placeholder="أخبرنا عن التحديات أو التطلعات الحالية لفريقك..." class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/15 text-sm focus:bg-white transition-colors"></textarea></div>
                    <div><button id="lead-submit-btn" type="submit" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 w-full sm:w-auto"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-send w-4 h-4 ml-2" aria-hidden="true"><path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"></path><path d="m21.854 2.147-10.94 10.939"></path></svg>أرسل الطلب</button></div></form></div>
            <div class="lg:col-span-4 space-y-6">
                <div class="p-6 sm:p-8 rounded-[16px] bg-[#0A0A0A] text-white border-[0.5px] border-white/10 space-y-6">
                    <div><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">قنوات الدعم</span>
                        <h3 class="text-xl font-bold font-arabic text-white mb-2">تواصل مباشر</h3>
                        <p class="text-xs sm:text-sm text-white/70 leading-relaxed">يمكنك أيضاً التواصل مع مسؤولي الحسابات لدينا مباشرة عبر القنوات المعتمدة:</p></div>
                    <div class="space-y-4 text-sm pt-2 border-t-[0.5px] border-white/10"><a href="mailto:contact@teamat.app" class="flex items-center gap-3 text-white/80 hover:text-[#C8FF00] transition-colors">
                        <div class="w-8 h-8 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mail w-4 h-4" aria-hidden="true"><path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"></path><rect x="2" y="4" width="20" height="16" rx="2"></rect></svg></div>
                        <div class="flex flex-col"><span class="text-[11px] text-white/50">البريد الإلكتروني</span><span dir="ltr" class="font-inter font-bold text-xs sm:text-sm text-right">contact@teamat.app</span></div></a><a href="https://wa.me/966500000000" target="_blank" rel="noopener noreferrer" class="flex items-center gap-3 text-white/80 hover:text-[#C8FF00] transition-colors">
                        <div class="w-8 h-8 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle w-4 h-4" aria-hidden="true"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"></path></svg></div>
                        <div class="flex flex-col"><span class="text-[11px] text-white/50">واتساب الأعمال</span><span dir="ltr" class="font-inter font-bold text-xs sm:text-sm text-right">+966 50 000 0000</span></div></a>
                        <div class="flex items-center gap-3 text-white/80 pt-2 border-t-[0.5px] border-white/10">
                            <div class="w-8 h-8 rounded-full bg-white/10 text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin w-4 h-4" aria-hidden="true"><path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"></path><circle cx="12" cy="10" r="3"></circle></svg></div>
                            <div class="flex flex-col"><span class="text-[11px] text-white/50">المقر</span><span class="text-xs sm:text-sm">تيمات — الرياض، المملكة العربية السعودية</span></div></div>
                        <div class="flex items-center gap-3 text-white/80">
                            <div class="w-8 h-8 rounded-full bg-white/10 text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-globe w-4 h-4" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"></path><path d="M2 12h20"></path></svg></div>
                            <div class="flex flex-col"><span class="text-[11px] text-white/50">الموقع الرسمي</span><span dir="ltr" class="font-inter text-xs sm:text-sm text-right">teamat.app</span></div></div></div></div></div></div></div></section>
@endsection
