@extends('layouts.marketing', [
    'headerTheme' => 'dark',
    'activeNav' => '/for-providers',
])

@section('title', 'تيمات | فعاليات متكررة تلقائياً للموظفين')
@section('description', 'انضم كشريك موثوق في شبكة تيمات واستقبل فعاليات مجدولة من كبرى الشركات في الرياض مع تسوية مالية واضحة.')

@section('content')
<script type="application/ld+json">{"@@context":"https://schema.org","@@type":"Organization","name":"تيمات | Teamat","url":"https://teamat.app","logo":"https://teamat.app/favicon.svg","description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة.","address":{"@@type":"PostalAddress","addressLocality":"الرياض","addressCountry":"SA"},"contactPoint":{"@@type":"ContactPoint","email":"contact@teamat.app","contactType":"customer support","areaServed":"SA","availableLanguage":["Arabic"]}}</script><script type="application/ld+json">{"@@context":"https://schema.org","@@type":"SoftwareApplication","name":"Teamat Platform | منصة تيمات","operatingSystem":"Web","applicationCategory":"BusinessApplication","offers":{"@@type":"Offer","price":"0","priceCurrency":"SAR","availability":"https://schema.org/InStock"},"description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة."}</script>
<section id="for-providers-hero" class="bg-[#0A0A0A] text-white pt-36 pb-20 px-4 sm:px-6 lg:px-8 border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -top-24 -right-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto relative z-10">
        <div class="max-w-[740px] space-y-4"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">شركاء المرافق والأنشطة</span>
            <h1 class="text-3xl sm:text-4xl md:text-5xl font-extrabold font-arabic text-white leading-tight">طلب متكرر، لا حجوزات متفرقة</h1>
            <p class="text-base sm:text-lg text-white/80 leading-[1.8] pt-1">استقبل مجموعات شركات مؤكدة وفق جداول ثابتة، واملأ فترات الإشغال المنخفض مع تسوية مالية دقيقة لكل فعالية مكتملة.</p>
            <div class="pt-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-4"><a class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 " href="/for-providers#join" data-discover="true">انضم كمزوّد خدمة</a><a class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-transparent text-[#C8FF00] border-[0.5px] border-[#C8FF00] hover:bg-[#C8FF00]/10 active:bg-[#C8FF00]/20 " href="/activities" data-discover="true">دليل الأنشطة</a></div></div></div></section>
<section id="provider-value-pillars" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">مزايا الشراكة</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-[#0A0A0A]">لماذا يفضل مزودو الخدمة الشراكة مع تيمات؟</h2></div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-repeat w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="m17 2 4 4-4 4"></path><path d="M3 11v-1a4 4 0 0 1 4-4h14"></path><path d="m7 22-4-4 4-4"></path><path d="M21 13v1a4 4 0 0 1-4 4H3"></path></svg></div>
                    <h3 class="text-xl font-bold font-arabic text-[#0A0A0A]">فعاليات مجدولة تتكرر</h3>
                    <p class="text-base text-[#0A0A0A]/70 leading-relaxed">مجتمعات الموظفين تمارس أنشطتها بانتظام دوري (أسبوعي/شهري)، مما يضمن تدفقاً متكرراً وثابتاً للإيرادات.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-building2 lucide-building-2 w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M10 12h4"></path><path d="M10 8h4"></path><path d="M14 21v-3a2 2 0 0 0-4 0v3"></path><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"></path><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"></path></svg></div>
                    <h3 class="text-xl font-bold font-arabic text-[#0A0A0A]">مجموعات مؤكدة من شركات</h3>
                    <p class="text-base text-[#0A0A0A]/70 leading-relaxed">التعامل مع مجموعات مؤسسية منظمة وملتزمة بالحضور والمواعيد دون إهدار لسعة المرفق.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-receipt w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z"></path><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path><path d="M12 17.5v-11"></path></svg></div>
                    <h3 class="text-xl font-bold font-arabic text-[#0A0A0A]">تسوية مالية واضحة</h3>
                    <p class="text-base text-[#0A0A0A]/70 leading-relaxed">تحويلات مالية دورية دقيقة ومطابقة لكل فعالية مكتملة دون تأخير أو خلافات محاسبية.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-calendar-check w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M8 2v4"></path><path d="M16 2v4"></path><rect width="18" height="18" x="3" y="4" rx="2"></rect><path d="M3 10h18"></path><path d="m9 16 2 2 4-4"></path></svg></div>
                    <h3 class="text-xl font-bold font-arabic text-[#0A0A0A]">تعبئة أوقات منخفضة الإشغال</h3>
                    <p class="text-base text-[#0A0A0A]/70 leading-relaxed">إمكانية توجيه فعاليات الشركات في الفترات التي تشهد طلباً منخفضاً لتحقيق الاستفادة القصوى من طاقتك الاستيعابية.</p></div></div></div></div></section>
<section id="provider-steps-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#0A0A0A] text-white border-t-[0.5px] border-b-[0.5px] border-white/10">
    <div aria-hidden="true" class="absolute rounded-full border-[20px] sm:border-[32px] border-[#C8FF00]/[0.05] pointer-events-none -bottom-32 -left-32 w-96 h-96 sm:w-[500px] sm:h-[500px]"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">خطوات الانضمام</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-white">كيف ينضم مزوّد الخدمة إلى شبكة تيمات؟</h2></div>
            <div id="step-flow" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-[#111111] text-white border-white/10 hover:border-[#C8FF00]/40">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">01</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-white">تقديم الطلب المبدئي</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-white/70">تعبئة النموذج بالمعلومات الأساسية حول المرفق وسعته وموقعه الجغرافي ونوع الأنشطة المقدمة.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-[#111111] text-white border-white/10 hover:border-[#C8FF00]/40">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">02</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-white">توثيق المرفق والخدمات</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-white/70">مراجعة معايير الجودة والتأكد من مطابقة المرفق لمتطلبات استضافة مجموعات الشركات.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-[#111111] text-white border-white/10 hover:border-[#C8FF00]/40">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">03</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-white">ضبط التوفّر والأسعار المعتمدة</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-white/70">تحديد فترات التوفّر والسعر الإجمالي للفعاليات وإدراجه في محرك اقتراحات النظام.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-[#111111] text-white border-white/10 hover:border-[#C8FF00]/40">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">04</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-white">استقبال أول فعالية</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-white/70">تلقي أول فعالية من مجتمع شركة وتأكيد الحضور وبدء الدورة المتكررة.</p></div></div></div></div></div></section>
<section id="provider-categories-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F0EDE6] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-8">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">نطاق الخدمات</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-[#0A0A0A]">الفئات التي نبحث عنها في شبكة تيمات</h2>
                <p class="text-[#0A0A0A]/80 text-base leading-[1.8]">نستقطب المرافق المتميزة في مدينة الرياض عبر عدة قطاعات حيوية:</p></div>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">رياضات المضرب (بادل، تنس، ريشة طائرة، إسكواش)</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">الملاعب الجماعية (كرة قدم، طائرة، سلة)</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">صالات اللياقة البدنية والكروس فيت المتخصصة</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">الأنشطة المائية والسباحة ومراكز التجديف</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">أنشطة المغامرات والتسلق ومسارات الرماية</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">مراكز الأنشطة الذهنية، غرف الألغاز، والألعاب اللوحية</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">استوديوهات الفنون والحرف وورش الطبخ التفاعلية</span></div>
                <div class="p-4 sm:p-5 rounded-[12px] bg-white border-[0.5px] border-[#0A0A0A]/10 flex items-center gap-3"><span class="w-6 h-6 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span class="text-sm sm:text-base font-bold text-[#0A0A0A]">صالات الرياضات الإلكترونية والمحاكاة التنافسية</span></div></div></div></div></section>
<section id="join" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="max-w-[800px] mx-auto space-y-8">
            <div class="text-center space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">سجّل مرفقك الآن</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-[#0A0A0A]">انضم كمزوّد خدمة معتمد</h2>
                <p class="text-[#0A0A0A]/70 text-base max-w-[560px] mx-auto">أدخل بيانات المرفق وسيتواصل معك فريق الشراكات خلال يومي عمل لإتمام التوثيق.</p></div>
            <form id="provider-application-form" novalidate="" class="p-6 sm:p-8 lg:p-10 rounded-[16px] bg-white border-[0.5px] border-[#0A0A0A]/10 space-y-6">
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                    <div><label for="provider-facility" class="block text-sm font-bold text-[#0A0A0A] mb-2">اسم المنشأة / المرفق <span class="text-red-500">*</span></label><input id="provider-facility" required="" placeholder="مثال: ملاعب أرينا الرياض" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors border-[#0A0A0A]/15" type="text" value=""></div>
                    <div><label for="provider-city" class="block text-sm font-bold text-[#0A0A0A] mb-2">المدينة <span class="text-red-500">*</span></label><select id="provider-city" required="" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/15 text-sm focus:bg-white transition-colors cursor-pointer"><option value="الرياض">الرياض (المرحلة الحالية)</option><option value="جدة">جدة (قريباً)</option><option value="المنطقة الشرقية">المنطقة الشرقية (قريباً)</option></select></div></div>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                    <div><label for="provider-activity" class="block text-sm font-bold text-[#0A0A0A] mb-2">نوع النشاط الأساسي <span class="text-red-500">*</span></label><select id="provider-activity" required="" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors cursor-pointer border-[#0A0A0A]/15"><option value="">اختر نوع النشاط</option><option value="padel-racket">رياضات المضرب (بادل، تنس، إسكواش)</option><option value="team-sports">ملاعب جماعية (كرة قدم، طائرة، سلة)</option><option value="fitness">لياقة بدنية وكروس فيت</option><option value="water">أنشطة مائية وسباحة</option><option value="adventure">مغامرات وتسلق ورماية</option><option value="mind-games">أنشطة ذهنية وغرف ألغاز وألعاب لوحية</option><option value="arts-cooking">فنون وحرف وورش طبخ</option><option value="esports">رياضات إلكترونية ومحاكاة</option><option value="other">أخرى</option></select></div>
                    <div><label for="provider-capacity" class="block text-sm font-bold text-[#0A0A0A] mb-2">السعة القصوى للفعالية الواحدة <span class="text-red-500">*</span></label><input id="provider-capacity" required="" placeholder="مثال: 20 إلى 50 شخصاً" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm focus:bg-white transition-colors border-[#0A0A0A]/15" type="text" value=""></div></div>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-5">
                    <div><label for="provider-contact-name" class="block text-sm font-bold text-[#0A0A0A] mb-2">اسم المشرف أو مسؤول المنشأة</label><input id="provider-contact-name" placeholder="الاسم" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/15 text-sm focus:bg-white transition-colors" type="text" value=""></div>
                    <div><label for="provider-phone" class="block text-sm font-bold text-[#0A0A0A] mb-2">رقم جوال التواصل <span class="text-red-500">*</span></label><input id="provider-phone" dir="ltr" required="" placeholder="05XXXXXXXX" class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] text-sm text-right focus:bg-white transition-colors border-[#0A0A0A]/15" type="tel" value=""></div></div>
                <div><label for="provider-notes" class="block text-sm font-bold text-[#0A0A0A] mb-2">ملاحظات عن المرفق أو أوقات التوفر المفضلة (اختياري)</label><textarea id="provider-notes" rows="3" placeholder="تفاصيل التجهيزات، التوفر الصباحي أو المسائي..." class="w-full px-4 py-3 rounded-[10px] bg-[#F6F8F5] text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/15 text-sm focus:bg-white transition-colors"></textarea></div>
                <div><button id="provider-submit-btn" type="submit" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 w-full sm:w-auto"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-building2 lucide-building-2 w-4 h-4 ml-2" aria-hidden="true"><path d="M10 12h4"></path><path d="M10 8h4"></path><path d="M14 21v-3a2 2 0 0 0-4 0v3"></path><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"></path><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"></path></svg>تقديم طلب الانضمام</button></div></form></div></div></section>
<section id="for-providers-cta" class="bg-[#0A0A0A] text-white py-16 sm:py-20 border-t-[0.5px] border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -bottom-24 -left-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div aria-hidden="true" class="absolute -top-24 -right-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 bg-[#111111] p-8 sm:p-12 rounded-[16px] border-[0.5px] border-white/10">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الخطوة القادمة</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold text-white leading-tight font-arabic">سجّل مرفقك مع تيمات وابدأ في استقبال فعاليات الشركات المجدولة</h2></div>
            <div class="shrink-0 w-full sm:w-auto"><a id="for-providers-cta-button" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 w-full sm:w-auto" href="/for-providers#join" data-discover="true">سجّل الآن</a></div></div></div></section>
@endsection
