@extends('layouts.marketing', [
    'headerTheme' => 'light',
    'activeNav' => '',
])

@section('title', 'تيمات | فعاليات متكررة تلقائياً للموظفين')
@section('description', 'تيمات تحوّل اهتمامات موظفيك إلى مجتمعات، والمجتمعات إلى فعاليات تتكرر تلقائياً دون الحاجة إلى منظّم بشري داخل الشركة.')

@section('content')
<script type="application/ld+json">{"@@context":"https://schema.org","@@type":"Organization","name":"تيمات | Teamat","url":"https://teamat.app","logo":"https://teamat.app/favicon.svg","description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة.","address":{"@@type":"PostalAddress","addressLocality":"الرياض","addressCountry":"SA"},"contactPoint":{"@@type":"ContactPoint","email":"contact@teamat.app","contactType":"customer support","areaServed":"SA","availableLanguage":["Arabic"]}}</script><script type="application/ld+json">{"@@context":"https://schema.org","@@type":"SoftwareApplication","name":"Teamat Platform | منصة تيمات","operatingSystem":"Web","applicationCategory":"BusinessApplication","offers":{"@@type":"Offer","price":"0","priceCurrency":"SAR","availability":"https://schema.org/InStock"},"description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة."}</script>
<section id="hero-section" class="min-h-[88vh] bg-[#F8FAF7] text-[#0A0A0A] pt-32 pb-16 lg:pb-24 px-4 sm:px-6 lg:px-8 flex items-center relative overflow-hidden border-b-[0.5px] border-[#0A0A0A]/10">
    <div aria-hidden="true" class="absolute -top-32 -left-32 w-96 h-96 sm:w-[540px] sm:h-[540px] rounded-full border-[28px] border-[#C8FF00]/20 pointer-events-none"></div>
    <div aria-hidden="true" class="absolute -bottom-40 -right-40 w-96 h-96 sm:w-[600px] sm:h-[600px] rounded-full border-[28px] border-[#0A0A0A]/[0.03] pointer-events-none"></div>
    <div class="max-w-[1180px] mx-auto w-full relative z-10">
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-center">
            <div class="lg:col-span-6 space-y-6"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">TEAMAT · SAUDI ARABIA</span>
                <h1 class="text-3xl sm:text-4xl md:text-5xl lg:text-[46px] xl:text-[50px] font-extrabold font-arabic text-[#0A0A0A] leading-[1.2] tracking-tight">الاهتمام المشترك لا يكفي — التكرار هو ما يبني الفريق</h1>
                <p class="text-base sm:text-lg text-[#0A0A0A]/80 font-normal leading-[1.8] max-w-[540px]">تيمات تحوّل اهتمامات موظفيك إلى مجتمعات، والمجتمعات إلى فعاليات تتكرر تلقائياً — دون أن يحتاج أحد إلى تنظيمها.</p>
                <div class="pt-2 flex flex-col sm:flex-row items-stretch sm:items-center gap-4"><a id="hero-primary-cta" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#0A0A0A] text-white border-[0.5px] border-[#0A0A0A] hover:bg-[#1a1a1a] hover:border-[#222222] " href="/contact" data-discover="true">اطلب عرضاً<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left w-4 h-4 ml-1" aria-hidden="true"><path d="m12 19-7-7 7-7"></path><path d="M19 12H5"></path></svg></a><a id="hero-secondary-cta" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-transparent text-[#0A0A0A] border-[0.5px] border-[#0A0A0A] hover:bg-[#0A0A0A]/5 active:bg-[#0A0A0A]/10 " href="/how-it-works" data-discover="true">كيف تعمل تيمات</a></div>
                <div class="pt-4 border-t-[0.5px] border-[#0A0A0A]/10 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs text-[#0A0A0A]/70 font-medium"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg><span>تثبيت حجز وإصدار فواتير ضريبية</span></span><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg><span>بدون أي جهود تنظيمية داخلية</span></span></div></div>
            <div class="lg:col-span-6 w-full">
                <div id="hero-floating-cards" class="w-full max-w-[500px] mx-auto lg:mr-auto lg:ml-0 text-right font-arabic">
                    <div class="flex items-center justify-between gap-2 mb-3"><span class="text-[11px] font-bold text-[#0A0A0A]/70">استعراض المجتمعات والفعاليات:</span>
                        <div class="flex items-center gap-1.5 overflow-x-auto no-scrollbar"><button type="button" class="px-3 py-1 rounded-full text-xs font-bold transition-all cursor-pointer border-[0.5px] whitespace-nowrap bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A] shadow-sm font-extrabold scale-[1.02]"><span class="ml-1">🎾</span><span>بادل</span></button><button type="button" class="px-3 py-1 rounded-full text-xs font-bold transition-all cursor-pointer border-[0.5px] whitespace-nowrap bg-white/80 text-[#0A0A0A]/70 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30 hover:text-[#0A0A0A]"><span class="ml-1">⚽</span><span>كرة القدم</span></button><button type="button" class="px-3 py-1 rounded-full text-xs font-bold transition-all cursor-pointer border-[0.5px] whitespace-nowrap bg-white/80 text-[#0A0A0A]/70 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30 hover:text-[#0A0A0A]"><span class="ml-1">♟️</span><span>شطرنج</span></button></div></div>
                    <div class="relative pt-3 pb-1">
                        <div class="absolute -inset-1.5 bg-[#C8FF00]/10 rounded-[28px] blur-md pointer-events-none"></div>
                        <div class="relative z-10 mx-3 p-4 rounded-[18px] bg-[#161616] text-white border-[0.5px] border-white/20 shadow-xl flex items-center justify-between gap-3">
                            <div class="flex items-center gap-3">
                                <div class="w-11 h-11 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center text-xl shrink-0 font-bold shadow-sm">🎾</div>
                                <div>
                                    <div class="flex items-center gap-2">
                                        <h4 class="text-sm sm:text-base font-extrabold text-white">مجتمع البادل</h4><span class="text-[10px] bg-[#C8FF00]/20 text-[#C8FF00] px-2 py-0.5 rounded-full font-bold border-[0.5px] border-[#C8FF00]/30">نشط</span></div>
                                    <p class="text-[11px] text-white/60 pt-0.5">28 موظفاً منضماً · الليدر: فهد السعيد</p></div></div>
                            <div class="text-left shrink-0"><span class="text-[10px] text-emerald-400 font-bold flex items-center gap-1 justify-end"><span class="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>تأكيد تلقائي</span><span class="text-[11px] text-white/50 block font-mono">مغطى من محفظة المجتمع</span></div></div>
                        <div class="relative z-20 -mt-2 p-5 sm:p-6 rounded-[22px] bg-[#0A0A0A] text-white border-[0.5px] border-white/20 shadow-2xl space-y-4.5">
                            <div class="flex items-start justify-between gap-2 border-b-[0.5px] border-white/10 pb-3">
                                <div><span class="text-[10px] font-extrabold font-inter text-[#C8FF00] uppercase tracking-wider block">UPCOMING EVENT · الفعالية القادمة</span>
                                    <h5 class="text-base sm:text-lg font-extrabold text-white mt-0.5">تأكيد حضور الجولة القادمة</h5></div><span class="px-2.5 py-1 rounded-full bg-[#C8FF00]/15 text-[#C8FF00] text-[11px] font-bold border-[0.5px] border-[#C8FF00]/30 shrink-0">حجز مؤكد</span></div>
                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5 text-xs">
                                <div class="p-3 rounded-[12px] bg-[#141414] border-[0.5px] border-white/10 flex items-center gap-3">
                                    <div class="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-[#C8FF00] shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-calendar w-4 h-4" aria-hidden="true"><path d="M8 2v4"></path><path d="M16 2v4"></path><rect width="18" height="18" x="3" y="4" rx="2"></rect><path d="M3 10h18"></path></svg></div>
                                    <div><span class="text-white/45 text-[10px] block">الموعد المحدد</span><span class="font-bold text-white text-xs">الخميس، 28 أغسطس</span><span class="text-[#C8FF00] text-[11px] font-mono block">08:00 م - 10:00 م</span></div></div>
                                <div class="p-3 rounded-[12px] bg-[#141414] border-[0.5px] border-white/10 flex items-center gap-3">
                                    <div class="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-[#C8FF00] shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin w-4 h-4" aria-hidden="true"><path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"></path><circle cx="12" cy="10" r="3"></circle></svg></div>
                                    <div><span class="text-white/45 text-[10px] block">المرفق والموقع</span><span class="font-bold text-white text-xs truncate block">بادل إن (Padel In)</span><span class="text-white/60 text-[11px] block">حي النرجس، الرياض</span></div></div></div>
                            <div class="p-3.5 rounded-[14px] bg-[#141414] border-[0.5px] border-white/10 space-y-2">
                                <div class="flex items-center justify-between text-xs"><span class="text-white/70 font-medium">اكتمال نصاب الحجز:</span><span class="text-[#C8FF00] font-bold font-mono">6 من 8 مقاعد مؤكدة (75%)</span></div>
                                <div class="w-full h-2 rounded-full bg-white/10 overflow-hidden" dir="ltr">
                                    <div class="h-full bg-[#C8FF00] rounded-full transition-all duration-300" style="width: 75%;"></div></div>
                                <div class="flex items-center justify-between text-[11px] text-white/50 pt-0.5"><span>متبقي 2 مقاعد للتأكيد</span><span class="font-mono text-white/70">متبقي 4 ساعات على الإغلاق</span></div></div>
                            <div class="space-y-2 pt-1"><button id="hero-floating-rsvp-btn" type="button" class="w-full py-3.5 px-4 rounded-full font-extrabold text-sm flex items-center justify-center gap-2 transition-all cursor-pointer border-[0.5px] shadow-lg bg-[#C8FF00] text-[#0A0A0A] border-[#C8FF00] hover:bg-[#bcf000] hover:scale-[1.01]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-zap w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path></svg><span>تأكيد الحضور بضغطة زر واحدة (RSVP)</span></button>
                                <div class="flex items-center justify-between text-[11px] text-white/50 px-1"><span class="flex items-center gap-1 text-white/70"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-check w-3.5 h-3.5 text-[#C8FF00]" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg>بدون مجموعات خارجية أو جمع مالي يدوي</span><span class="font-mono text-[#C8FF00] text-[10px]">تأكيد فوري</span></div></div></div></div></div></div></div></div></section>
<section id="problem-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#0A0A0A] text-white border-b-[0.5px] border-white/10">
    <div aria-hidden="true" class="absolute rounded-full border-[20px] sm:border-[32px] border-[#C8FF00]/[0.05] pointer-events-none -bottom-32 -left-32 w-96 h-96 sm:w-[500px] sm:h-[500px]"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">التحدي الحقيقي</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[36px] font-extrabold font-arabic text-white">المنظّم المفقود</h2>
                <p class="text-white/80 text-base sm:text-[17px] leading-[1.8]">كل شركة جرّبت النشاط الجماعي تعرف النمط: فعالية أولى ناجحة، ثم صمت. السبب ليس ضعف الحماس — بل أن الاستمرار كان معلّقاً على شخص واحد يتطوّع بوقته. عندما ينشغل، يتوقف كل شيء.</p></div>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden undefined border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4 bg-[#141414] border-white/10">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-flame w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">الحماس يبدأ ثم ينطفئ</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">تبدأ الفكرة بنشاط واحد بحضور عالٍ، لكن بدون بنية تقنية تتولى التكرار، تتلاشى التجربة تدريجياً وتعود الفرق إلى عزلتها اليومية.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden undefined border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4 bg-[#141414] border-white/10">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">التنسيق عبء إضافي على موظف</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">البحث عن مواعيد وتأكيد مشاركات وجمع المبالغ يستهلك ساعات عمل من موظف متطوّع لم يُعيَّن لهذه المهمة في الأساس.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden undefined border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-4 bg-[#141414] border-white/10">
                    <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chart-column w-6 h-6 text-[#0A0A0A]" aria-hidden="true"><path d="M3 3v16a2 2 0 0 0 2 2h16"></path><path d="M18 17V9"></path><path d="M13 17V5"></path><path d="M8 17v-3"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">لا بيانات تُثبت الأثر</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">الأنشطة التقليدية تتم خارج أي سياق موثّق، فلا تملك الشركة أي مؤشرات تقيس تفاعل الموظفين أو تكرار مشاركتهم.</p></div></div></div></div></section>
<section id="how-it-works-steps" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">دورة النظام</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[36px] font-extrabold font-arabic text-[#0A0A0A]">كيف تضمن تيمات الاستمرار التلقائي</h2></div>
            <div id="step-flow" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">01</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-[#0A0A0A]">تفعيل الحساب</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-[#0A0A0A]/70">الشركة تفتح حسابها وتحدد مسارها المالي وتدعو موظفيها عبر مسار دخول سريع برمز يصل عبر واتساب.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">02</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-[#0A0A0A]">تكوّن المجتمعات</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-[#0A0A0A]/70">الموظفون يحددون اهتماماتهم الفعلية وينضمّون تلقائياً إلى مجتمعات متخصصة داخل نطاق الشركة.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">03</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-[#0A0A0A]">فعالية متكررة تلقائياً</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-[#0A0A0A]/70">المجتمع يولّد فعاليته مع مزوّد الخدمة المناسب بجدول ثابت وتأكيد توفّر وتثبيت مسبق للسعر الإجمالي.</p></div></div>
                <div class="p-6 sm:p-7 rounded-[16px] border-[0.5px] flex flex-col justify-between relative transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30">
                    <div>
                        <div class="flex items-center justify-between mb-4"><span class="font-inter font-extrabold text-2xl text-[#C8FF00]">04</span><span class="w-2 h-2 rounded-full bg-[#C8FF00]"></span></div>
                        <h3 class="text-lg sm:text-xl font-bold font-arabic mb-3 text-[#0A0A0A]">الحضور والقياس</h3>
                        <p class="text-sm sm:text-[15px] leading-relaxed text-[#0A0A0A]/70">الحضور يُسجَّل تلقائياً عند اكتمال الفعالية، وتنعكس مؤشرات التفاعل مباشرة في لوحة متابعة الشركة.</p></div></div></div></div></div></section>
<section id="community-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#0A0A0A] text-white border-t-[0.5px] border-b-[0.5px] border-white/10">
    <div aria-hidden="true" class="absolute rounded-full border-[20px] sm:border-[32px] border-[#C8FF00]/[0.05] pointer-events-none top-1/2 -translate-y-1/2 -right-40 w-96 h-96 sm:w-[600px] sm:h-[600px]"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الهيكل التقني</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[36px] font-extrabold font-arabic text-white">المجتمع هو وحدة البناء</h2>
                <p class="text-white/80 text-base sm:text-[17px] leading-[1.8]">المجتمع في تيمات ليس مجموعة محادثة — بل كيان له قادة ومحفظة وجدول فعاليات. هذا ما يجعل التكرار خاصية في النظام لا مجهوداً بشرياً.</p></div>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users w-5 h-5" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><path d="M16 3.128a4 4 0 0 1 0 7.744"></path><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><circle cx="9" cy="7" r="4"></circle></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">قادة المجتمع</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">أعضاء يملكون صلاحية جدولة الفعاليات وتأكيد الحضور مع نافذة تصحيح مدتها ٢٤ ساعة.</p></div>
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield w-5 h-5" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">محفظة مخصصة</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">سجل مالي ثابت لكل مجتمع، يضمن وضوح الصرف والتسوية المالية الفورية مع مزوّد الخدمة.</p></div>
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-repeat w-5 h-5" aria-hidden="true"><path d="m17 2 4 4-4 4"></path><path d="M3 11v-1a4 4 0 0 1 4-4h14"></path><path d="m7 22-4-4 4-4"></path><path d="M21 13v1a4 4 0 0 1-4 4H3"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">توليد تلقائي للفعاليات</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">جدولة دورية وفق توفّر المرفق وسعته المعتمدة دون الحاجة لمتابعة يدوية.</p></div></div></div></div></section>
<section id="tracks-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">المرونة المالية</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[36px] font-extrabold font-arabic text-[#0A0A0A]">مساران ماليان يناسبان هيكل ميزانيتك</h2>
                <p class="text-[#0A0A0A]/80 text-base sm:text-[17px] leading-[1.8]">تختار الشركة المسار المالي الذي يلائم سياستها التشغيلية، مع الحفاظ على تجربة مستخدم موحدة للموظفين.</p></div>
            <div id="track-compare" class="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div class="p-8 sm:p-10 rounded-[16px] bg-[#0A0A0A] text-white border-[0.5px] border-white/15 flex flex-col justify-between relative overflow-hidden">
                    <div>
                        <div class="flex items-center justify-between mb-6">
                            <div class="w-12 h-12 rounded-full bg-[#C8FF00] flex items-center justify-center text-[#0A0A0A]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-wallet w-6 h-6" aria-hidden="true"><path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"></path><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"></path></svg></div><span class="text-[11px] font-inter font-extrabold uppercase tracking-[1.5px] py-1 px-3.5 rounded-full bg-white/10 text-[#C8FF00] border-[0.5px] border-[#C8FF00]/30">تحمّل كامل للأنشطة</span></div>
                        <h3 class="text-2xl sm:text-3xl font-extrabold font-arabic text-white mb-3">محفظة المجتمع</h3>
                        <p class="text-white/70 text-base leading-relaxed mb-6">الشركة تشحن رصيداً في محفظة المجتمعات، ويُخصم ثمن كل فعالية منه تلقائياً عند اكتمالها.</p>
                        <div class="p-4 rounded-[12px] bg-white/5 border-[0.5px] border-white/10 mb-6"><span class="text-xs font-bold text-[#C8FF00] block mb-1">الخيار الأمثل لـ:</span>
                            <p class="text-xs sm:text-sm text-white/80 leading-relaxed">الأنسب للشركات التي تتحمّل تكلفة الأنشطة بالكامل وتضع ميزانية محددة للتفاعل.</p></div>
                        <ul class="space-y-3 mb-6">
                            <li class="flex items-center gap-3 text-sm text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>شحن رصيد مسبق للمجتمعات</span></li>
                            <li class="flex items-center gap-3 text-sm text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>خصم مباشر عند اكتمال الفعالية</span></li>
                            <li class="flex items-center gap-3 text-sm text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>تحكّم كامل في سقف الميزانية</span></li></ul></div></div>
                <div class="p-8 sm:p-10 rounded-[16px] bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/15 flex flex-col justify-between relative overflow-hidden">
                    <div>
                        <div class="flex items-center justify-between mb-6">
                            <div class="w-12 h-12 rounded-full bg-[#0A0A0A] flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users w-6 h-6" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><path d="M16 3.128a4 4 0 0 1 0 7.744"></path><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><circle cx="9" cy="7" r="4"></circle></svg></div><span class="text-[11px] font-inter font-extrabold uppercase tracking-[1.5px] py-1 px-3.5 rounded-full bg-[#0A0A0A]/5 text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/20">توسّع بتكلفة ثابتة</span></div>
                        <h3 class="text-2xl sm:text-3xl font-extrabold font-arabic text-[#0A0A0A] mb-3">دفع الموظف</h3>
                        <p class="text-[#0A0A0A]/70 text-base leading-relaxed mb-6">الشركة تدفع مقابل استخدام النظام فقط، بينما يدفع كل موظف حصته المحددة عن كل فعالية يشارك فيها.</p>
                        <div class="p-4 rounded-[12px] bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 mb-6"><span class="text-xs font-bold text-[#0A0A0A] block mb-1">الخيار الأمثل لـ:</span>
                            <p class="text-xs sm:text-sm text-[#0A0A0A]/80 leading-relaxed">الأنسب للتوسّع الواسع في الشركات الكبيرة بتكلفة تشغيلية ثابتة ومدروسة.</p></div>
                        <ul class="space-y-3 mb-6">
                            <li class="flex items-center gap-3 text-sm text-[#0A0A0A]/90"><span class="w-5 h-5 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>الشركة تدفع رسوم النظام فقط</span></li>
                            <li class="flex items-center gap-3 text-sm text-[#0A0A0A]/90"><span class="w-5 h-5 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>الموظف يدفع حصة الفرد للفعالية</span></li>
                            <li class="flex items-center gap-3 text-sm text-[#0A0A0A]/90"><span class="w-5 h-5 rounded-full bg-[#0A0A0A] text-[#C8FF00] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>مرونة عالية في عدد الفعاليات</span></li></ul></div></div></div></div></div></section>
<section id="managed-coordinator-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F0EDE6] text-[#0A0A0A] border-t-[0.5px] border-b-[0.5px] border-[#0A0A0A]/10">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="p-8 sm:p-12 rounded-[16px] bg-[#0A0A0A] text-white border-[0.5px] border-white/10 relative overflow-hidden">
            <div class="max-w-[700px] space-y-6">
                <div class="inline-flex items-center gap-2"><span class="text-[11px] font-inter font-extrabold uppercase tracking-[2px] py-1 px-3 rounded-full bg-[#C8FF00] text-[#0A0A0A]">خدمة اختيارية</span></div>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-white leading-snug">المنسّق المُدار</h2>
                <p class="text-white/80 text-base sm:text-lg leading-[1.8]">لا يوجد داخل فريقك من يملك وقت التنسيق؟ المنسّق المُدار خدمة اختيارية يتولّى فيها فريق تيمات إدارة مجتمعاتك وجدولة فعالياتها ومتابعة موفري الخدمة بالكامل.</p>
                <ul class="space-y-3 pt-2">
                    <li class="flex items-center gap-3 text-sm sm:text-base text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>إدارة وتنشيط المجتمعات وجداولها</span></li>
                    <li class="flex items-center gap-3 text-sm sm:text-base text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>التنسيق المستمر مع مزودي الخدمة وتثبيت المواعيد</span></li>
                    <li class="flex items-center gap-3 text-sm sm:text-base text-white/90"><span class="w-5 h-5 rounded-full bg-[#C8FF00] text-[#0A0A0A] flex items-center justify-center shrink-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check w-3.5 h-3.5" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></span><span>متابعة الحضور وإصدار تقارير دورية لمسؤول الحساب في الشركة</span></li></ul></div></div></div></section>
<section id="providers-intro-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-white text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 bg-[#F6F8F5] p-8 sm:p-10 rounded-[16px] border-[0.5px] border-[#0A0A0A]/10">
            <div class="max-w-[600px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">شبكة الملاعب والمرافق</span>
                <h2 class="text-2xl sm:text-3xl font-extrabold font-arabic text-[#0A0A0A]">شبكة موثوقة من مزودي الخدمة</h2>
                <p class="text-[#0A0A0A]/70 text-base leading-relaxed">نربط مجتمعات الشركات بأفضل المرافق الرياضية والإبداعية والترفيهية في الرياض مع التزام كامل بتثبيت الأسعار والتسوية الدقيقة.</p></div>
            <div class="shrink-0"><a id="providers-intro-btn" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[15px] py-3 px-6 font-bold bg-[#0A0A0A] text-white border-[0.5px] border-[#0A0A0A] hover:bg-[#1a1a1a] hover:border-[#222222] " href="/for-providers" data-discover="true">تعرّف على نموذج مزودي الخدمة<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left w-4 h-4 ml-1" aria-hidden="true"><path d="m12 19-7-7 7-7"></path><path d="M19 12H5"></path></svg></a></div></div></div></section>
<section id="home-cta-band" class="bg-[#0A0A0A] text-white py-16 sm:py-20 border-t-[0.5px] border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -bottom-24 -left-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div aria-hidden="true" class="absolute -top-24 -right-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 bg-[#111111] p-8 sm:p-12 rounded-[16px] border-[0.5px] border-white/10">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الخطوة القادمة</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold text-white leading-tight font-arabic">ابدأ بمجتمع واحد واختبر التكرار التلقائي في شركتك</h2></div>
            <div class="shrink-0 w-full sm:w-auto"><a id="home-cta-band-button" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 w-full sm:w-auto" href="/contact" data-discover="true">اطلب عرضاً</a></div></div></div></section>
@endsection
