@extends('layouts.marketing', [
    'headerTheme' => 'dark',
    'activeNav' => '/how-it-works',
])

@section('title', 'تيمات | فعاليات متكررة تلقائياً للموظفين')
@section('description', 'تعرّف على آلية عمل منصة تيمات خطوة بخطوة للشركات، الموظفين، ومزودي الخدمة، وضمانات اكتمال الفعالية والشفافية المالية.')

@section('content')
<script type="application/ld+json">{"@@context":"https://schema.org","@@type":"Organization","name":"تيمات | Teamat","url":"https://teamat.app","logo":"https://teamat.app/favicon.svg","description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة.","address":{"@@type":"PostalAddress","addressLocality":"الرياض","addressCountry":"SA"},"contactPoint":{"@@type":"ContactPoint","email":"contact@teamat.app","contactType":"customer support","areaServed":"SA","availableLanguage":["Arabic"]}}</script><script type="application/ld+json">{"@@context":"https://schema.org","@@type":"SoftwareApplication","name":"Teamat Platform | منصة تيمات","operatingSystem":"Web","applicationCategory":"BusinessApplication","offers":{"@@type":"Offer","price":"0","priceCurrency":"SAR","availability":"https://schema.org/InStock"},"description":"منصة B2B SaaS سعودية تحوّل الاهتمامات المشتركة بين الموظفين إلى فعاليات متكررة تلقائياً دون الحاجة إلى مجهود تنظيمي داخل الشركة."}</script>
<section id="how-it-works-hero" class="bg-[#0A0A0A] text-white pt-36 pb-20 px-4 sm:px-6 lg:px-8 border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -top-24 -right-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto relative z-10">
        <div class="max-w-[720px] space-y-4"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الآلية خطوة بخطوة</span>
            <h1 class="text-3xl sm:text-4xl md:text-5xl font-extrabold font-arabic text-white leading-tight">من الاهتمام إلى الفعالية المتكررة</h1>
            <p class="text-base sm:text-lg text-white/80 leading-[1.8] pt-1">بنية تقنية متكاملة تربط الشركة والموظف ومزوّد الخدمة في مسار تلقائي خالٍ من التعقيد والتنسيق اليدوي.</p></div></div></section>
<section id="three-parties-journey" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-10">
            <div class="flex flex-wrap items-center justify-center gap-3"><button type="button" class="flex items-center gap-2 px-6 py-3 rounded-full text-sm sm:text-base font-bold transition-colors select-none cursor-pointer border-[0.5px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-building2 lucide-building-2 w-4 h-4" aria-hidden="true"><path d="M10 12h4"></path><path d="M10 8h4"></path><path d="M14 21v-3a2 2 0 0 0-4 0v3"></path><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"></path><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"></path></svg><span>الشركة</span></button><button type="button" class="flex items-center gap-2 px-6 py-3 rounded-full text-sm sm:text-base font-bold transition-colors select-none cursor-pointer border-[0.5px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user w-4 h-4" aria-hidden="true"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg><span>الموظف</span></button><button type="button" class="flex items-center gap-2 px-6 py-3 rounded-full text-sm sm:text-base font-bold transition-colors select-none cursor-pointer border-[0.5px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] bg-white text-[#0A0A0A] border-[#0A0A0A]/10 hover:border-[#0A0A0A]/30"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-store w-4 h-4" aria-hidden="true"><path d="M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5"></path><path d="M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244"></path><path d="M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05"></path></svg><span>مزوّد الخدمة</span></button></div>
            <div class="max-w-[760px] mx-auto pt-4 space-y-8">
                <div class="text-center space-y-2">
                    <h2 class="text-2xl sm:text-3xl font-extrabold font-arabic text-[#0A0A0A]">رحلة مسؤول الحساب في الشركة</h2></div>
                <div id="step-flow" class="relative space-y-6 sm:space-y-8">
                    <div aria-hidden="true" class="absolute top-6 bottom-6 right-6 sm:right-7 w-[2px] bg-[#C8FF00]/40 -z-0"></div>
                    <div class="relative flex items-start gap-4 sm:gap-6 z-10 group">
                        <div class="shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center font-inter font-extrabold text-sm sm:text-base border-[0.5px] select-none bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]">01</div>
                        <div class="flex-1 p-5 sm:p-6 rounded-[16px] border-[0.5px] transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 group-hover:border-[#0A0A0A]/30">
                            <h3 class="text-lg sm:text-xl font-bold font-arabic mb-2 text-[#0A0A0A]">تفعيل الحساب وضبط الإعدادات</h3>
                            <p class="text-sm sm:text-base leading-relaxed text-[#0A0A0A]/70">إنشاء حساب الشركة، وتعيين مسؤولي الحساب، وضبط سياسات المجموعات ونطاقات العمل.</p></div></div>
                    <div class="relative flex items-start gap-4 sm:gap-6 z-10 group">
                        <div class="shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center font-inter font-extrabold text-sm sm:text-base border-[0.5px] select-none bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]">02</div>
                        <div class="flex-1 p-5 sm:p-6 rounded-[16px] border-[0.5px] transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 group-hover:border-[#0A0A0A]/30">
                            <h3 class="text-lg sm:text-xl font-bold font-arabic mb-2 text-[#0A0A0A]">اختيار المسار المالي</h3>
                            <p class="text-sm sm:text-base leading-relaxed text-[#0A0A0A]/70">تحديد مسار محفظة المجتمع (شحن مسبق) أو مسار دفع الموظف (رسوم النظام فقط).</p></div></div>
                    <div class="relative flex items-start gap-4 sm:gap-6 z-10 group">
                        <div class="shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center font-inter font-extrabold text-sm sm:text-base border-[0.5px] select-none bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]">03</div>
                        <div class="flex-1 p-5 sm:p-6 rounded-[16px] border-[0.5px] transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 group-hover:border-[#0A0A0A]/30">
                            <h3 class="text-lg sm:text-xl font-bold font-arabic mb-2 text-[#0A0A0A]">دعوة الموظفين</h3>
                            <p class="text-sm sm:text-base leading-relaxed text-[#0A0A0A]/70">إرسال رابط التفعيل للموظفين للدخول السريع عبر رمز يصل في رسالة واتساب.</p></div></div>
                    <div class="relative flex items-start gap-4 sm:gap-6 z-10 group">
                        <div class="shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center font-inter font-extrabold text-sm sm:text-base border-[0.5px] select-none bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]">04</div>
                        <div class="flex-1 p-5 sm:p-6 rounded-[16px] border-[0.5px] transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 group-hover:border-[#0A0A0A]/30">
                            <h3 class="text-lg sm:text-xl font-bold font-arabic mb-2 text-[#0A0A0A]">اعتماد المجتمعات</h3>
                            <p class="text-sm sm:text-base leading-relaxed text-[#0A0A0A]/70">مراجعة واعتماد المجتمعات المكوّنة وتعيين قادتها وتحديد سقوف الإنفاق إن وُجدت.</p></div></div>
                    <div class="relative flex items-start gap-4 sm:gap-6 z-10 group">
                        <div class="shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center font-inter font-extrabold text-sm sm:text-base border-[0.5px] select-none bg-[#0A0A0A] text-[#C8FF00] border-[#0A0A0A]">05</div>
                        <div class="flex-1 p-5 sm:p-6 rounded-[16px] border-[0.5px] transition-colors bg-white text-[#0A0A0A] border-[#0A0A0A]/10 group-hover:border-[#0A0A0A]/30">
                            <h3 class="text-lg sm:text-xl font-bold font-arabic mb-2 text-[#0A0A0A]">متابعة المؤشرات الحية</h3>
                            <p class="text-sm sm:text-base leading-relaxed text-[#0A0A0A]/70">الاطلاع على الفعاليات المكتملة ومعدلات التفاعل ونمو المجتمعات عبر لوحة تحكّم موثّقة.</p></div></div></div></div></div></div></section>
<section id="completion-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#0A0A0A] text-white border-t-[0.5px] border-b-[0.5px] border-white/10">
    <div aria-hidden="true" class="absolute rounded-full border-[20px] sm:border-[32px] border-[#C8FF00]/[0.05] pointer-events-none -bottom-32 -left-32 w-96 h-96 sm:w-[500px] sm:h-[500px]"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">دقة التوثيق</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-white">ماذا يحدث عند اكتمال الفعالية؟</h2>
                <p class="text-white/80 text-base sm:text-lg leading-[1.8]">وحدة القيمة في تيمات هي «الفعالية المكتملة». عندما تنتهي الفعالية، تبدأ دورة تقنية محددة تضمن الدقة التامة:</p></div>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-big w-5 h-5" aria-hidden="true"><path d="M21.801 10A10 10 0 1 1 17 3.335"></path><path d="m9 11 3 3L22 4"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">تسجيل الحضور التلقائي</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">يُسجّل حضور المشاركين المؤكدين تلقائياً كمدخل أساسي في سجلات المنصة ولوحة الشركة.</p></div>
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-check w-5 h-5" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">نافذة تصحيح مدتها ٢٤ ساعة</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">يملك قادة المجتمع ومسؤول الحساب في الشركة نافذة مدتها ٢٤ ساعة لتعديل أي حالة حضور قبل إغلاق السجل نهائياً.</p></div>
                <div class="p-6 sm:p-7 rounded-[16px] bg-[#111111] border-[0.5px] border-white/10 space-y-3">
                    <div class="w-10 h-10 rounded-full bg-[#C8FF00]/15 border-[0.5px] border-[#C8FF00]/30 flex items-center justify-center text-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-spreadsheet w-5 h-5" aria-hidden="true"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"></path><path d="M14 2v4a2 2 0 0 0 2 2h4"></path><path d="M8 13h2"></path><path d="M14 13h2"></path><path d="M8 17h2"></path><path d="M14 17h2"></path></svg></div>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-white">تحديث مؤشرات التفاعل</h3>
                    <p class="text-sm sm:text-base text-white/70 leading-relaxed">تُحتسب الفعالية المكتملة في معدلات التفاعل الإجمالية وسجل المجتمع دون أي تدخل يدوي.</p></div></div></div></div></section>
<section id="transparency-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F0EDE6] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-12">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">النزاهة والوضوح</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-[#0A0A0A]">الشفافية المالية في تيمات</h2>
                <p class="text-[#0A0A0A]/80 text-base sm:text-lg leading-[1.8]">لا مفاجآت في الفواتير ولا رسوم خفية. نلتزم بقواعد محاسبية واضحة تحمي جميع الأطراف:</p></div>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-3"><span class="font-inter font-extrabold text-xl text-[#0A0A0A] block">01</span>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-[#0A0A0A]">تثبيت السعر الإجمالي</h3>
                    <p class="text-sm sm:text-base text-[#0A0A0A]/70 leading-relaxed">السعر الإجمالي للفعالية يُثبَّت عند إنشائها ولا يتغيّر بتغيّر عدد المشاركين الحاضرين.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-3"><span class="font-inter font-extrabold text-xl text-[#0A0A0A] block">02</span>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-[#0A0A0A]">سجل مالي ثابت</h3>
                    <p class="text-sm sm:text-base text-[#0A0A0A]/70 leading-relaxed">كل فعالية تولّد رقماً مرجعياً وسجلاً مالياً غير قابل للتعديل يوضح المسار وقيمة الفعالية.</p></div>
                <div class="rounded-[16px] transition-colors duration-150 relative overflow-hidden bg-white text-[#0A0A0A] border-[0.5px] border-[#0A0A0A]/10 p-6 sm:p-7 space-y-3"><span class="font-inter font-extrabold text-xl text-[#0A0A0A] block">03</span>
                    <h3 class="text-lg sm:text-xl font-bold font-arabic text-[#0A0A0A]">سياسة استرداد واضحة</h3>
                    <p class="text-sm sm:text-base text-[#0A0A0A]/70 leading-relaxed">في حال إلغاء الفعالية وفق الشروط الزمنية المعتمدة، تعود المبالغ مباشرة إلى محفظة المجتمع أو وسيلة الدفع الأصلية.</p></div></div></div></div></section>
<section id="faq-section" class="relative py-12 md:py-16 lg:py-[72px] overflow-hidden bg-[#F6F8F5] text-[#0A0A0A] ">
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10 ">
        <div class="space-y-10">
            <div class="text-center max-w-[640px] mx-auto space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#0A0A0A] ">الأسئلة الشائعة</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold font-arabic text-[#0A0A0A]">كل ما تحتاج معرفته عن آلية عمل تيمات</h2></div>
            <div id="faq-accordion" class="space-y-4 max-w-[800px] mx-auto">
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white border-[#0A0A0A]/30"><button id="faq-btn-0" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="true" aria-controls="faq-ans-0"><span class="font-arabic leading-snug">كيف تضمن تيمات استمرار الفعاليات دون منظّم بشري؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 rotate-180 bg-[#C8FF00]"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button>
                    <div id="faq-ans-0" role="region" aria-labelledby="faq-btn-0" class="px-6 pb-6 pt-1 text-sm sm:text-base text-[#0A0A0A]/75 leading-relaxed border-t-[0.5px] border-[#0A0A0A]/5">
                        <p>النظام يعتمد على بنية المجتمع ذاتية الإدارة، حيث يتم ربط الاهتمامات بجدول زمني متكرر ومزوّد خدمة معتمد، مع تنبيهات وتأكيدات حضور آلية تحافظ على وتيرة النشاط.</p></div></div>
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white/80 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/20"><button id="faq-btn-1" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="false" aria-controls="faq-ans-1"><span class="font-arabic leading-snug">ما الفرق بين محفظة المجتمع ودفع الموظف؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button></div>
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white/80 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/20"><button id="faq-btn-2" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="false" aria-controls="faq-ans-2"><span class="font-arabic leading-snug">كيف يسجّل الموظفون دخولهم إلى المنصة؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button></div>
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white/80 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/20"><button id="faq-btn-3" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="false" aria-controls="faq-ans-3"><span class="font-arabic leading-snug">ما هي صلاحيات مسؤول الحساب في الشركة؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button></div>
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white/80 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/20"><button id="faq-btn-4" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="false" aria-controls="faq-ans-4"><span class="font-arabic leading-snug">متى تصبح الفعالية «مكتملة» وتُحسب في المؤشرات؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button></div>
                <div class="rounded-[16px] border-[0.5px] transition-colors duration-150 overflow-hidden bg-white/80 border-[#0A0A0A]/10 hover:border-[#0A0A0A]/20"><button id="faq-btn-5" type="button" class="w-full py-5 px-6 text-right flex items-center justify-between gap-4 font-bold text-base sm:text-lg text-[#0A0A0A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] select-none" aria-expanded="false" aria-controls="faq-ans-5"><span class="font-arabic leading-snug">ما هي خدمة المنسّق المُدار ومتى تحتاجها الشركة؟</span><span class="w-8 h-8 rounded-full bg-[#F6F8F5] border-[0.5px] border-[#0A0A0A]/10 flex items-center justify-center shrink-0 transition-transform duration-200 "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4 text-[#0A0A0A]" aria-hidden="true"><path d="m6 9 6 6 6-6"></path></svg></span></button></div></div></div></div></section>
<section id="how-it-works-cta" class="bg-[#0A0A0A] text-white py-16 sm:py-20 border-t-[0.5px] border-b-[0.5px] border-white/10 relative overflow-hidden">
    <div aria-hidden="true" class="absolute -bottom-24 -left-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div aria-hidden="true" class="absolute -top-24 -right-24 w-80 h-80 rounded-full border-[24px] border-[#C8FF00]/[0.04] pointer-events-none"></div>
    <div class="max-w-[1120px] mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 bg-[#111111] p-8 sm:p-12 rounded-[16px] border-[0.5px] border-white/10">
            <div class="max-w-[640px] space-y-3"><span class="inline-block font-inter text-[11px] font-extrabold uppercase tracking-[2.5px] mb-3 select-none text-[#C8FF00] ">الخطوة القادمة</span>
                <h2 class="text-2xl sm:text-3xl lg:text-[34px] font-extrabold text-white leading-tight font-arabic">اطلب عرضاً مخصصاً لشركتك وشاهد كيف تعمل تيمات على أرض الواقع</h2></div>
            <div class="shrink-0 w-full sm:w-auto"><a id="how-it-works-cta-button" class="inline-flex items-center justify-center gap-2 rounded-full whitespace-nowrap transition-colors duration-150 select-none cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C8FF00] disabled:opacity-50 disabled:cursor-not-allowed text-[16px] py-3.5 px-7 font-bold bg-[#C8FF00] text-[#0A0A0A] border-[0.5px] border-[#C8FF00] hover:bg-[#bcf200] hover:border-[#bcf200] active:opacity-90 w-full sm:w-auto" href="/contact" data-discover="true">اطلب عرضاً</a></div></div></div></section>
@endsection
