const statusLabels: Record<string, string> = {
    active: 'نشط',
    pending: 'قيد المراجعة',
    approved: 'مقبول',
    rejected: 'مرفوض',
    review: 'مراجعة',
    // آلة حالات الفعالية (H §9 — A7)
    pending_approval: 'بانتظار الاعتماد',
    open: 'مفتوح',
    pending_provider: 'بانتظار رد المزوّد',
    provider_alternative: 'وقت بديل مقترح',
    booked: 'محجوزة — التسجيل مفتوح',
    awaiting_payment: 'بانتظار الدفع',
    confirmed: 'مؤكد',
    in_progress: 'جارية الآن',
    completed: 'مكتمل',
    settled: 'مسوّاة',
    expired: 'منتهية دون اكتمال العدد',
    cancelled_min_not_met: 'ملغاة — لم يبلغ الحد الأدنى',
    cancelled_provider: 'ملغاة من المزوّد',
    cancelled_company: 'ملغاة من الشركة',
    cancelled_payment_failed: 'ملغاة — فشل التحصيل',
    cancelled: 'ملغي',
    inactive: 'غير نشط',
    dormant: 'خامل',
    closed: 'مغلق',
    maintenance: 'صيانة',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    // كشف التسوية وفاتورة رسوم النظام (H §12.7/§12.8 — A11)
    draft: 'مسودة',
    issued: 'مُصدَرة',
    void: 'ملغاة',
    included: 'ضمن كشف',
    disputed: 'معترض عليه',
    adjusted: 'مُصحَّح',
    provisional: 'مبدئية',
    real: 'نهائية',
    // حقول المشارك الثلاثة (H §10 — A7)
    reserved: 'محجوز',
    waitlisted: 'قائمة الانتظار',
    released: 'أُخلي المقعد',
    not_due: 'غير مستحق',
    due: 'مستحق',
    failed: 'فشل الدفع',
    refunded: 'مسترد',
    attended: 'حاضر',
    absent: 'غائب',
    suspended: 'معلّق',
};

export default function StatusBadge({ status }: { status: string }) {
    const label = statusLabels[status] ?? status;
    return <span className={`badge b-${status}`}>{label}</span>;
}
